/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/onboarding` | `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/onboarding/components/AddressStep` | `/onboarding/components/AddressStep`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/onboarding/components/ConsentsStep` | `/onboarding/components/ConsentsStep`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/onboarding/components/DocumentStep` | `/onboarding/components/DocumentStep`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/onboarding/components/ProfileStep` | `/onboarding/components/ProfileStep`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/onboarding/components/ReviewStep` | `/onboarding/components/ReviewStep`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/onboarding/components` | `/onboarding/components`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/onboarding` | `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/onboarding/components/AddressStep` | `/onboarding/components/AddressStep`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/onboarding/components/ConsentsStep` | `/onboarding/components/ConsentsStep`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/onboarding/components/DocumentStep` | `/onboarding/components/DocumentStep`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/onboarding/components/ProfileStep` | `/onboarding/components/ProfileStep`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/onboarding/components/ReviewStep` | `/onboarding/components/ReviewStep`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/onboarding/components` | `/onboarding/components`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/onboarding${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/onboarding/components/AddressStep${`?${string}` | `#${string}` | ''}` | `/onboarding/components/AddressStep${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/onboarding/components/ConsentsStep${`?${string}` | `#${string}` | ''}` | `/onboarding/components/ConsentsStep${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/onboarding/components/DocumentStep${`?${string}` | `#${string}` | ''}` | `/onboarding/components/DocumentStep${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/onboarding/components/ProfileStep${`?${string}` | `#${string}` | ''}` | `/onboarding/components/ProfileStep${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/onboarding/components/ReviewStep${`?${string}` | `#${string}` | ''}` | `/onboarding/components/ReviewStep${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/onboarding/components${`?${string}` | `#${string}` | ''}` | `/onboarding/components${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/onboarding` | `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/onboarding/components/AddressStep` | `/onboarding/components/AddressStep`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/onboarding/components/ConsentsStep` | `/onboarding/components/ConsentsStep`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/onboarding/components/DocumentStep` | `/onboarding/components/DocumentStep`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/onboarding/components/ProfileStep` | `/onboarding/components/ProfileStep`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/onboarding/components/ReviewStep` | `/onboarding/components/ReviewStep`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/onboarding/components` | `/onboarding/components`; params?: Router.UnknownInputParams; };
    }
  }
}
